version: '3.3'
services:
  web:
    restart: always
    image: prototype2:latest
    build: https://github.com/ViniciusEduardoCruzMoura/prototype_2.git
    environment:
      - CONFIG_DEBUG=${CONFIG_DEBUG}
      - CONFIG_SECRET_KEY=${CONFIG_SECRET_KEY}
      - CONFIG_ALLOWED_HOSTS=${CONFIG_ALLOWED_HOSTS}
      - CONFIG_CSRF_TRUSTED_ORIGINS=${CONFIG_CSRF_TRUSTED_ORIGINS}
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:5005"
  nginx:
    restart: always
    image: nginx:latest
    ports:
      - "5085:5085"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on: 
      - web