version: '3.3'
services:
  nginx:
    restart: always
    image: nginx:latest
    ports:
      - ${PORT:-9001}:80
    volumes:
      - nginx:/etc/nginx/conf.d
      - static:/static
      - media:/media
    depends_on: 
      - web
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 32M
  web:
    restart: always
    image: pet_adoption_manager:${VERSION:-latest}
    build: .
    environment:
      - DOCKER_BUILDKIT=0
      - CONFIG_DEBUG=${CONFIG_DEBUG}
      - CONFIG_SECRET_KEY=${CONFIG_SECRET_KEY}
      - CONFIG_ALLOWED_HOSTS=${CONFIG_ALLOWED_HOSTS}
      - CONFIG_CSRF_TRUSTED_ORIGINS=${CONFIG_CSRF_TRUSTED_ORIGINS}
      - CONFIG_POSTGRESQL_NAME=${CONFIG_POSTGRESQL_NAME}
      - CONFIG_POSTGRESQL_USER=${CONFIG_POSTGRESQL_USER}
      - CONFIG_POSTGRESQL_PASSWORD=${CONFIG_POSTGRESQL_PASSWORD}
      - CONFIG_POSTGRESQL_HOST=${CONFIG_POSTGRESQL_HOST}
      - CONFIG_POSTGRESQL_PORT=${CONFIG_POSTGRESQL_PORT}
      - CONFIG_REDIS_URL=${CONFIG_REDIS_URL}
    # command: >
    #   sh -c "python manage.py migrate &&
    #          python manage.py collectstatic --noinput &&
    #          gunicorn --config gunicorn-cfg.py core.wsgi"
    volumes:
      - static:/usr/src/static
      - media:/usr/src/media
      - nginx:/usr/src/nginx
    depends_on:
      - redis
      - postgres
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: 128M
        reservations:
          cpus: '0.10'
          memory: 64M
  redis:
    restart: always
    image: redis
    volumes:
      - redis:/data
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 32M
  postgres:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data/
    environment:
      - PGUSER=postgres
      - PGPORT=${CONFIG_POSTGRESQL_PORT:-5432}
      - POSTGRES_DB=${CONFIG_POSTGRESQL_NAME:-postgres}
      - POSTGRES_PASSWORD=${CONFIG_POSTGRESQL_PASSWORD:-postgres}
      - POSTGRES_USER=${CONFIG_POSTGRESQL_USER:-postgres}
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 832M
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1m30s
      timeout: 30s
      retries: 3
volumes:
  static:
  media:
  redis:
  postgres:
  nginx:
