# Generated by Django 4.1.5 on 2023-10-08 20:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adopter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Adotador',
                'verbose_name_plural': 'Adotadores',
                'db_table': 'management_system_adopter',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Nome')),
                ('observation', models.CharField(blank=True, default=None, max_length=4000, null=True, verbose_name='Observação')),
                ('pub_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Date de publicação')),
                ('gender', models.CharField(blank=True, choices=[('m', 'Macho'), ('f', 'Fêmea')], default=None, max_length=6, null=True, verbose_name='Gênero')),
                ('age', models.IntegerField(blank=True, default=None, null=True, verbose_name='Idade')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animais',
                'db_table': 'management_system_animal',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AnimalSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_size', models.CharField(max_length=50, verbose_name='Tamanho do Animal')),
            ],
            options={
                'verbose_name': 'Tamanho do Animal',
                'verbose_name_plural': 'Tamanhos dos Animais',
                'db_table': 'management_system_animalsize',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AnimalStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_status', models.CharField(max_length=50, verbose_name='Situação do Animal')),
            ],
            options={
                'verbose_name': 'Situação do Animal',
                'verbose_name_plural': 'Situações dos Animais',
                'db_table': 'management_system_animalstatus',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AnimalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_type', models.CharField(max_length=50, verbose_name='Tipo de Animal')),
            ],
            options={
                'verbose_name': 'Tipo de Animal',
                'verbose_name_plural': 'Tipos de Animais',
                'db_table': 'management_system_animaltype',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed_type', models.CharField(max_length=50, verbose_name='Raça')),
            ],
            options={
                'verbose_name': 'Raça',
                'verbose_name_plural': 'Raças',
                'db_table': 'management_system_breed',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Cor',
                'verbose_name_plural': 'Cores',
                'db_table': 'management_system_color',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Telephone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddd', models.CharField(max_length=50, verbose_name='DDD')),
                ('numero', models.CharField(max_length=50, verbose_name='Numero')),
            ],
            options={
                'verbose_name': 'Telefone',
                'verbose_name_plural': 'Telefones',
                'db_table': 'management_system_telephone',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('animal', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_management_system.animal', verbose_name='Animais')),
            ],
            options={
                'verbose_name': 'Vacina',
                'verbose_name_plural': 'Vacinas',
                'db_table': 'management_system_vaccine',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, default=None, null=True, upload_to='uploads', verbose_name='Arquivo')),
                ('animal', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_management_system.animal', verbose_name='Animais')),
            ],
            options={
                'verbose_name': 'Imagem',
                'verbose_name_plural': 'Imagens',
                'db_table': 'management_system_images',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='animal',
            name='breed',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_management_system.breed', verbose_name='Raça'),
        ),
        migrations.AddField(
            model_name='animal',
            name='color',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_management_system.color', verbose_name='Cor'),
        ),
        migrations.AddField(
            model_name='animal',
            name='size',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_management_system.animalsize', verbose_name='Tamanho'),
        ),
        migrations.AddField(
            model_name='animal',
            name='status',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_management_system.animalstatus', verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='animal',
            name='type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_management_system.animaltype', verbose_name='Tipo de Animal'),
        ),
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Inscrição')),
                ('aprobada', models.BooleanField(default=False, verbose_name='Aprovada')),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True, verbose_name='Data de Aprovação')),
                ('adopter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_management_system.adopter')),
                ('animal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_management_system.animal')),
            ],
            options={
                'verbose_name': 'Adoção',
                'verbose_name_plural': 'Adoções',
                'db_table': 'management_system_adoption',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='adopter',
            name='phone',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_management_system.telephone', verbose_name='Telefone'),
        ),
    ]
